# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 423)
        MainWindow.setStyleSheet("QWidget {border-radius:8px;background-color:#FFF0F5;color:#A4D3EE;font:bold;}\n"
"QPushButton {background-color:#FFE4E1;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 351, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 12, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 13, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 6, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 7, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 9, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 10, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 11, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 12, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 3, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 3, 4, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 4, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 4, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 4, 4, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 5, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 5, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 5, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 6, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 6, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 6, 4, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 7, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 7, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 7, 4, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 8, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 8, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 8, 4, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 9, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 9, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 9, 4, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 10, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 10, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 10, 4, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 11, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 11, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 11, 4, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 12, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 12, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 12, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 380, 101, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "第7位"))
        self.label_3.setText(_translate("MainWindow", "名 次"))
        self.label_13.setText(_translate("MainWindow", "第6位"))
        self.label_7.setText(_translate("MainWindow", "正确率"))
        self.label_6.setText(_translate("MainWindow", "正确量"))
        self.label_4.setText(_translate("MainWindow", "名 字"))
        self.label_16.setText(_translate("MainWindow", "第9位"))
        self.label_15.setText(_translate("MainWindow", "第8位"))
        self.label_17.setText(_translate("MainWindow", "第10位"))
        self.label_12.setText(_translate("MainWindow", "第5位"))
        self.label_9.setText(_translate("MainWindow", "第2位"))
        self.label_11.setText(_translate("MainWindow", "第4位"))
        self.label_10.setText(_translate("MainWindow", "第3位"))
        self.label_5.setText(_translate("MainWindow", "测试量"))
        self.label_8.setText(_translate("MainWindow", "第1位"))
        self.label.setText(_translate("MainWindow", "共 20 个,对 0 个，错 20 个"))
        self.label_18.setText(_translate("MainWindow", "你这回在第 999 名"))
        self.label_2.setText(_translate("MainWindow", "正确率0.00%"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.label_31.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "TextLabel"))
        self.label_37.setText(_translate("MainWindow", "TextLabel"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.label_39.setText(_translate("MainWindow", "TextLabel"))
        self.label_40.setText(_translate("MainWindow", "TextLabel"))
        self.label_41.setText(_translate("MainWindow", "TextLabel"))
        self.label_42.setText(_translate("MainWindow", "TextLabel"))
        self.label_43.setText(_translate("MainWindow", "TextLabel"))
        self.label_44.setText(_translate("MainWindow", "TextLabel"))
        self.label_45.setText(_translate("MainWindow", "TextLabel"))
        self.label_46.setText(_translate("MainWindow", "TextLabel"))
        self.label_47.setText(_translate("MainWindow", "TextLabel"))
        self.label_48.setText(_translate("MainWindow", "TextLabel"))
        self.label_49.setText(_translate("MainWindow", "TextLabel"))
        self.label_50.setText(_translate("MainWindow", "TextLabel"))
        self.label_51.setText(_translate("MainWindow", "TextLabel"))
        self.label_52.setText(_translate("MainWindow", "TextLabel"))
        self.label_53.setText(_translate("MainWindow", "TextLabel"))
        self.label_54.setText(_translate("MainWindow", "TextLabel"))
        self.label_55.setText(_translate("MainWindow", "TextLabel"))
        self.label_56.setText(_translate("MainWindow", "TextLabel"))
        self.label_57.setText(_translate("MainWindow", "TextLabel"))
        self.label_58.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "返回"))


